config/routes.rb
 Rails.application.routes.draw do
  get 'sessions/new', to: 'sessions#new', as: "new_login"
  post 'sessions/create', to: 'sessions#create', as: 'login'
  delete 'sessions/logout', to: 'sessions#logout', as: 'logout'


  resources :users
  resources :animes
  # resources :trackeds
  resources :reviews
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
    # has_many :trackeds
    # has_many :user_trackeds, through: :trackeds, source: :users
    has_many :reviews
    has_many :users, through: :reviews
    # has_many :trackeds
    # has_many :users, through: :trackeds
    # has_many :reviews
    # has_many :users, through: :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :anime
    belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :anime
    belongs_to :user
    validates :rating, length: { in: 1..100 }
    validates :comment, presence: :true
    validates_uniqueness_of :anime_id, scope: :user_id, :message => "This anime already has a review from you."
end

app/models/tracked.rb
class Tracked < ApplicationRecord
    belongs_to :anime
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    # has_many :trackeds
    # has_many :tracked_animes, through: :trackeds, source: :user
    has_many :reviews
    has_many :animes, through: :reviews
    # validates :user, uniqueness: :true
    has_secure_password



end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController

    def index
    @animes = Anime.all
    end

    def show
    @anime = Anime.find(params[:id])   
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_reviews, only: [:edit, :update, :destroy]
    def new
        @review = Review.new
    end
    def create 
        @review = @current_user.reviews.build(review_params)
        if @review.save
            redirect_to user_path(@review.user_id)
        else
            flash[:my_error] = @review.errors.full_messages
            redirect_to new_review_path
        end
    end
    
    def edit;end
    
    def update
        if @review.update(review_params)
        redirect_to user_path(@review.user)
    else
        flash[:my_error] = @review.errors.full_messages
        redirect_to edit_review_path
    end
    end

    def destroy
        # find_reviews
    end
private
    def find_reviews
        @review = Review.find(params[:id])
    end

    def review_params
        params.require(:review).permit(:user_id, :anime_id, :rating, :comment, :comment_likes)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
# skip_before_action :authorized, only: [:new, :create]

  
  def new
  end

  def logout
    session.delete(:user_id)
    redirect_to new_login_path
  end
  

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user&& @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = "Username or Password is Incorrect"
      redirect_to new_login_path
    end
  end
end

app/controllers/trackeds_controller.rb
class TrackedsController < ApplicationController
    before_action :find_tracked, only: [:edit, :update, :destroy]
   
    def new
        @tracked = Tracked.new
    end

    def edit;end

    def create 
        tracked = Tracked.create(tracked_params)   
            redirect_to @tracked 
        else
            render 'new'
        end
    end

    def update
        @tracked.update(tracked_params)
        redirect_to tracked_path(@tracked)
    end

    def destroy
        # find_tracked
    end
private
    def find_tracked
        @tracked = Tracked.find(params[:id])
    end

    def tracked_params
        params.require(:tracked).permit(:user_id, :anime_id, :rating)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :user_find, only: [:show, :edit, :update]
     
    def new
        @user = User.new
    end
    
    def edit;end
    def show;end  
    
    def create
        @user = User.create(user_params)
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end
    
    def update
        @user.update(user_params)
        redirect_to user_path(@user)
    end 
private
    def user_params
        params.require(:user).permit(:name, :password, :bio, :birthday, :post_count, :life_spent_on_anime)
    end
    def user_find
      @user =  User.find(params[:id])
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/index.html.erb
<div class="anime_list">
    <% @animes.each do |anime| %>
        <div class="index-tile">
            <img class="index-img" src="<%=anime.poster_image%>" alt="" style="width:210px;height:180px;object-fit: cover;">
            <span><%= link_to anime.title, anime_path(anime) %></span>
        </div>
    <%end%>
</div>

app/views/animes/show.html.erb
<div class="anime_title"><%= @anime.title %></div>
<div class="show-left">
      <div class="anime_date">
        <%= @anime.start_date %> -
        <%= @anime.end_date %>
    </div>
    <img class="show-img" src="<%= @anime.poster_image %>" alt="<%= @anime.poster_image %>" style="width:600px;height:400px;object-fit: cover;">
  
    <div class="synopsis"><%= @anime.synopsis %></div>
</div>

<div class="show-right">
    <div class="average_rating">Average User Score  <%=@anime.average_rating %></div><br>
    <div class="reviews">
        <% @anime.reviews.each do |review|%>
        <div class="review_item">
            <div> User Rating (out of 10): <%= review.rating %></div>
            <div> User comment: <%= review.comment %> </div>
        </div>
        <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceCowboy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="main-container">
    <div class='header'>
      SPACE COWBOY
    </div>
    <div class='nav'>
      <ul class='nav-ul'> 
          <% if @current_user %>
          <li> Welcome <%= @current_user.name %>! </li>
          <li><%= link_to 'All Animes', animes_path %></li>
          <li><%= link_to 'My Profile', user_path(@current_user)%></li>
          <li><%= link_to 'Write A Review', new_review_path %></li>
          <li><%= link_to 'Sign Out', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'All Animes', animes_path %></li>
          <li><%= link_to 'Create An Account', new_user_path%></li>
          <li><%= link_to 'Sign-In!', new_login_path%></li>
        <% end %>
      </ul>
    </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<% if flash[:my_error]%>
    <%flash[:my_error].each do |error|%>
    <%=error%>
    <%end%>
<%end%>

<div class="review-form-page"
<%= form_for @review do |f| %>

<%= f.collection_select :anime_id, Anime.all, :id, :title %>

<p>
<%= f.label :comment %>
<%= f.text_field :comment %>
</p>

<p>
<%= f.label :rating_out_of_100%>
<%= f.text_field(:rating, in: 1..100)%>
</p>

<p>
<%= f.submit %>
</p>
<div>
<%end %>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/users/_form.html.erb
<% if flash[:my_error]%>
    <%flash[:my_error].each do |error|%>
    <%=error%>
    <%end%>
<%end%>

<%= form_for @user do |f| %>
<p class="sign-up-form">

    <%= f.label :username %>
    <%= f.text_field :name %>


    <%= f.label :password %>
    <%= f.password_field :password %>


    <%= f.label :bio %>
    <%= f.text_field :bio %>

    <%= f.label :birthday %>
    <%= f.date_select(:birthday, order: [:month, :day, :year], start_year: Date.today.year - 80, end_year: Date.today.year - 1) %>

    <%= f.submit %>
    
</p>
<% end %>

app/views/users/show.html.erb
<div class="user-bio-show-left">
    <div class="show-page-username">Hi, <%=@user.name.capitalize%>! </div><br>
        <div class="show-avatar-section">
            Birthdate: <%= @user.birthday %> <br>
            <br>
            Post Count: <%= @user.reviews.count%> <br>
            <br>
            Life Spent Watching Anime (mins): <%= @user.life_spent_on_anime%><br>
            <br>
            Bio: <%= @user.bio %> <br>
        </div>
    
</div>

<div class="user-bio-show-right">
    <div class="prev-review-header"> Previously Reviewed</div>   

        
    <div class="prev-reviewed-anime-title">          
            <% @user.reviews.each do |review| %>
            <%=review.anime.title%>
            <%= link_to "0", anime_path(review.anime) %><br>
    </div>
    

    <div class="prev-reviewed-list">
        Your Score: <%=review.rating%> <br>
        <%=review.comment%>
        <%= button_to "Edit Review", edit_review_path(review), method: :get%><br>
        <%end%>                  
    </div>    
</div>  
 